# Generated by Django 5.1 on 2024-09-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=120)),
                ('caddress', models.TextField()),
                ('cdescription', models.TextField()),
                ('cnumber', models.PositiveSmallIntegerField()),
                ('cstatus', models.BooleanField(verbose_name='Online')),
            ],
        ),
    ]
