# Generated by Django 5.1 on 2024-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('contactNumber', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(verbose_name='Online')),
            ],
        ),
    ]
