# Generated by Django 5.1 on 2024-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contactNumber',
            field=models.PositiveSmallIntegerField(max_length=11),
        ),
    ]
