# Generated by Django 5.1 on 2024-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnumber',
            field=models.PositiveSmallIntegerField(max_length=15),
        ),
    ]
