# Generated by Django 5.1 on 2024-09-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cstatus',
        ),
    ]
