# Generated by Django 5.1 on 2024-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0002_remove_contact_cstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='caddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
