# Generated by Django 5.1 on 2024-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0003_alter_contact_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnumber',
            field=models.CharField(max_length=5),
        ),
    ]
