# Generated by Django 5.1 on 2024-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0004_rename_product_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(verbose_name='Online'),
        ),
    ]
