# Generated by Django 5.1 on 2024-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0004_alter_contact_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnumber',
            field=models.CharField(max_length=16),
        ),
    ]
