# Generated by Django 5.1 on 2024-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0005_alter_contact_cnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cemail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cpersonel',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cweb',
            field=models.CharField(max_length=30),
        ),
    ]
