# Generated by Django 5.1 on 2024-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactlist', '0007_alter_contact_cemail_alter_contact_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cnumber',
            field=models.CharField(max_length=16),
        ),
    ]
